### ISSUE TITLE
Docker version?

### ISSUE THREAD

**Issue by gerroon** [huytd/pomoday-v2#2]
Hi
Any chance of docker version?

thanks

**Comment by ff4500** [comment]
@gerroon You could always pull down the repo, build it according to the instructions and copy your `dist` folder to your server... then run an nginx instance in docker in that folder.

Here's a compose file that I just used to set it up for myself like that:

`docker-compose.yml`

```
version: '3'
services:
  pomoday:
    container_name: pomoday
    image: nginx:alpine
    ports:
      - "8983:80"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./dist:/usr/share/nginx/html
```

This assumes that you have a directory that contains your `dist` folder and your `docker-compose.yml` at the top level.

**Comment by gerroon** [comment]
Yes and not everyone understands all that stuff.  Docker makes it easy for everyone else, like non techie users.

Thanks for the compose file I will try it.

**Comment by ff4500** [comment]
@huytd Upcoming DB integration sounds great. Can't wait! I have ideas about building this into a browser start page (with the added ability to add shortcuts, etc) for my own use. Being able to pair this up with a DB would help a lot.

Of note on my compose file above, it's mapping the port to 8983. Feel free to leave it at 80 to use the default nginx port, or change it to something else. I already have other things on the server I plopped it on, so changing the port was a must do. Going to reverse proxy it with Traefik and will post another complete compose file for that, if anyone else is interested.

**Comment by ff4500** [comment]
Ok, here's a simple compose file for anyone running Traefik already:

`docker-compose.yml`
```
version: '3'
networks:
  proxy:
    external: true
services:
  pomoday:
    container_name: pomoday
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pomoday"
      - "traefik.frontend.rule=Host:your.domainname.com"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - proxy
```
